name: Deploy MiniProgram
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install miniprogram-ci -g
      - name: Write private key
        run: |
          printf "%s" "${{ secrets.PRIVATE_KEY }}" > private.key
      - name: Upload to WeChat
        run: |
          miniprogram-ci upload \
            --pp ./miniprogram \
            --pkp ./private.key \
            --appid ${{ secrets.APPID }} \
            --uv ${{ secrets.APPID }} \
            --enable-es6 true \
            --enable-autoprefixwxss true \
            --upload-version "1.0.${{ github.run_number }}"
